# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PcfyMyMac < Formula
  desc "Get the PC-like experience on macOS"
  homepage "https://github.com/raxigan/pcfy-my-mac"
  version "0.0.6"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/raxigan/pcfy-my-mac/releases/download/0.0.6/pcfy-my-mac-0.0.6-darwin-arm64.tar.gz"
      sha256 "96002884706564322b34495aa36103fb0e2e2a4888bafc02bda73417bd9b08ff"

      def install
        bin.install "pcfy-my-mac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raxigan/pcfy-my-mac/releases/download/0.0.6/pcfy-my-mac-0.0.6-darwin-amd64.tar.gz"
      sha256 "351851f331be66926f99e8db95c88bec50bf6f5d55a98627080479040de318c5"

      def install
        bin.install "pcfy-my-mac"
      end
    end
  end
end
