# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PcfyMyMac < Formula
  desc "Get the PC-like experience on macOS"
  homepage "https://github.com/raxigan/pcfy-my-mac"
  version "0.2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/raxigan/pcfy-my-mac/releases/download/0.2.0/pcfy-my-mac-0.2.0-darwin-amd64.tar.gz"
    sha256 "5b95463d14e0f09613c22d0f281a7ab983183f970d3dd56268e90929008d7a55"

    def install
      bin.install "pcfy-my-mac"
    end
  end
  on_arm do
    url "https://github.com/raxigan/pcfy-my-mac/releases/download/0.2.0/pcfy-my-mac-0.2.0-darwin-arm64.tar.gz"
    sha256 "5a3b479e26407c326ef24ef699be4c86685125302041a1295ab6ffab15063797"

    def install
      bin.install "pcfy-my-mac"
    end
  end
end
